CREATE DATABASE CZBook;
GO

USE CZBook;
GO

CREATE TABLE TipoUsuario
(
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	NomeTipoUsuario VARCHAR (60) UNIQUE NOT NULL
);
GO

CREATE TABLE Usuario
(
	Idusuario INT PRIMARY KEY IDENTITY,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario),
	Email VARCHAR(100) UNIQUE NOT NULL,
	Senha VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Autor
(
	IdAutor INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario),
	Nome VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Empresa
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	NomeFantasia VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Categoria
(
	IdCategoria INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(100) NOT NULL
);
GO

CREATE TABLE livro
(
	IdLivro INT PRIMARY KEY IDENTITY,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa),
	IdCategoria INT FOREIGN KEY REFERENCES Categoria(IdCategoria),
	IdAutor INT FOREIGN KEY REFERENCES Autor(IdAutor),
	Titulo VARCHAR(100) NOT NULL,
	Sinopse VARCHAR(100) NOT NULL,
	DataPublicação DATE NOT NULL,
	Preço VARCHAR(50) NOT NULL
);
GO